# Generated by Django 5.0.2 on 2024-02-27 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("noteyApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionAnswerTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("distractors", models.JSONField()),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="noteyApp.topictable",
                    ),
                ),
            ],
        ),
    ]
