# Generated by Django 5.0.2 on 2024-02-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noteyApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.TextField()),
                ("topic_id", models.IntegerField()),
            ],
        ),
    ]
