# Generated by Django 5.0.2 on 2024-02-23 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noteyApp", "0002_topictable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contexttable",
            name="id",
        ),
        migrations.RemoveField(
            model_name="topictable",
            name="id",
        ),
        migrations.AddField(
            model_name="contexttable",
            name="index",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="contexttable",
            name="topic_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="noteyApp.topictable"
            ),
        ),
        migrations.AlterField(
            model_name="topictable",
            name="topic_id",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
