# Generated by Django 5.0.2 on 2024-03-03 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("noteyApp", "0003_leaderboardtable_userquiztable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userquiztable",
            name="userAnswers",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="StatsTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quizzesTaken", models.IntegerField()),
                ("questionsAttempted", models.IntegerField()),
                ("questionsCorrect", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
