# Generated by Django 5.0.2 on 2024-03-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("noteyApp", "0004_userquiztable_useranswers_statstable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statstable",
            name="questionsAttempted",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="statstable",
            name="questionsCorrect",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="statstable",
            name="quizzesTaken",
            field=models.IntegerField(default=0),
        ),
    ]
